title: Fixie
description: A simple and minimal portfolio theme for Jekyll

url: https://brianmaierjr.com/fixie
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

collections:
  portfolio:
    output: true
    permalink: /portf/:path/

navigation:
 - title: Home
   url: /index.html
 - title: Portfolio
   url: /portfolio
 - title: About Us
   url: /about-us
 - title: Contact Us
   url: /contact-us

social:
 - icon: icon-twitter.svg
   url: https://twitter.com/brianmaierjr
 - icon: icon-facebook.svg
   url: https://facebook.com/brianmaierjr
 - icon: icon-instagram.svg
   url: https://instagram.com/brian_maier_jr
 - icon: icon-github.svg
   url: https://github.com/brianmaierjr

google_analytics: "UA-58263416-1"
